version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: dev-cluster
      CASSANDRA_DC: datacenter1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: app
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_DATA_CASSANDRA_PORT: 9042
      SPRING_DATA_CASSANDRA_KEYSPACE_NAME: my_keyspace
      SPRING_DATA_CASSANDRA_LOCAL_DATACENTER: datacenter1
